services:
    _defaults:
        autowire: true      # automatically injects dependencies
        autoconfigure: true # automatically register services

    # define autowiring services for App namespace
    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    # exception event subscriber (error handling functionality)
    App\Event\Subscriber\ExceptionEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # request middlewares
    # --------------------------------------------------------------------------------- #
    # escape request data (for security)
    App\Middleware\EscapeRequestDataMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 1 }

    # check if database is online
    App\Middleware\DatabaseOnlineMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 2 }
